<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Maheshs-MacBook-Pro.local" failures="0" tests="10" name="Tests.LogInTest" time="34.474" errors="1" timestamp="27 Apr 2018 09:06:53 GMT" skipped="0">
  <testcase classname="Tests.LogInTest" name="loginUILetsGetStarted" time="0.056"/>
  <testcase classname="Tests.LogInTest" name="loginUIProceedButtonText" time="0.048"/>
  <testcase classname="Tests.LogInTest" name="loginUIMobileRadio" time="0.059"/>
  <testcase classname="Tests.LogInTest" name="loginUIUsernameLabelText" time="0.060"/>
  <testcase classname="Tests.LogInTest" name="loginUsingEmail" time="25.873">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Tests.LogInTest.loginUsingEmail(LogInTest.java:92)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- loginUsingEmail -->
  <testcase classname="Tests.LogInTest" name="loginUIUsernameRadioButton" time="0.054"/>
  <testcase classname="Tests.LogInTest" name="loginUIEmailRadioButton" time="8.169"/>
  <testcase classname="Tests.LogInTest" name="loginUIForgotPasswordLinkText" time="0.060"/>
  <testcase classname="Tests.LogInTest" name="loginUISignUpButtonText" time="0.050"/>
  <testcase classname="Tests.LogInTest" name="loginUIPasswordLabelText" time="0.045"/>
</testsuite> <!-- Tests.LogInTest -->
